{% set version = "1.2.3" %}

package:
    name: historydict
    version: {{ version }}

source:
    url: https://github.com/Nikea/historydict/archive/v{{ version }}.tar.gz
    fn: historydict-v{{ version }}.tar.gz
    sha256: be81625a2423faad11314b21619f45815e441fe4b244735ff868fbc15a586c94

build:
    noarch: python
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - historydict
    requires:
        - pytest
    source_files:
        - test*.py
    commands:
        - py.test -vrxs

about:
    home: https://github.com/Nikea/historydict
    license: BSD 3-Clause
    summary: A persistent dictionary with history backed by sqlite

extra:
    recipe-maintainers:
        - ericdill
        - licode
        - tacaswell
        - CJ-Wright
