{% set version = "1.2.1" %}

package:
    name: historydict
    version: {{ version }}

source:
    url: https://github.com/Nikea/historydict/archive/v{{ version }}.tar.gz
    fn: historydict-v{{ version }}.tar.gz
    sha256: e5c18cf3f7e12053fcedddbbedf5769d8af89794b54937e8297f96b3fa4a4cf2

build:
    noarch: python
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
    run:
        - python

test:
    imports:
        - historydict
    requires:
        - pytest
    source_files:
        - test*.py
    commands:
        - py.test -vrxs

about:
    home: https://github.com/Nikea/historydict
    license: BSD 3-Clause
    summary: A persistent dictionary with history backed by sqlite

extra:
    recipe-maintainers:
        - ericdill
        - licode
        - tacaswell
        - CJ-Wright
