{% set version = "1.2.6" %}

package:
  name: historydict
  version: {{ version }}

source:
  url: https://github.com/Nikea/historydict/archive/v{{ version }}.tar.gz
  fn: historydict-v{{ version }}.tar.gz
  sha256: 4dcc24b8f314623a9d139e3ac910c42746497d2e4cc58b7f112c82099efbc2a7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - historydict
  requires:
    - pytest
  source_files:
    - test*.py
  commands:
    - py.test -vrxs

about:
  home: https://github.com/Nikea/historydict
  license: BSD-3-Clause
  summary: A persistent dictionary with history backed by sqlite
  license_file: LICENSE

extra:
  recipe-maintainers:
    - licode
    - tacaswell
    - CJ-Wright
    - mrakitin
