{% set version = "1.2.0" %}

package:
    name: historydict
    version: {{ version }}

source:
    url: https://github.com/Nikea/historydict/archive/v{{ version }}.tar.gz
    fn: historydict-v{{ version }}.tar.gz
    sha256: c59d19badded9c2a0b61fd1cd570e94da43446d17f9aa7a4179321f6635ee903

build:
    noarch: python
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
    run:
        - python

test:
    imports:
        - historydict
    requires:
        - pytest
    test_source:
        - tests/*
    commands:
        - py.test -vrxs

about:
    home: https://github.com/Nikea/historydict
    license: BSD 3-Clause
    summary: A persistent dictionary with history backed by sqlite

extra:
    recipe-maintainers:
        - ericdill
        - licode
        - tacaswell
        - CJ-Wright
