{% set version = "1.2.4" %}

package:
  name: historydict
  version: {{ version }}

source:
  url: https://github.com/Nikea/historydict/archive/v{{ version }}.tar.gz
  fn: historydict-v{{ version }}.tar.gz
  sha256: 69b27f978649386a29e989877c2b9b8b02a9c1785531c53a4fa1815f75e386a1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - historydict
  requires:
    - pytest
  source_files:
    - test*.py
  commands:
    - py.test -vrxs

about:
  home: https://github.com/Nikea/historydict
  license: BSD-3-Clause
  summary: A persistent dictionary with history backed by sqlite

extra:
  recipe-maintainers:
    - licode
    - tacaswell
    - CJ-Wright
