travis:
  secure:
    BINSTAR_TOKEN: OGwLCoG6Fg9ipsS5xa6vg30p0G6Jl7Y5eGtnf8B0TC7NZNsbr53HwC/HjKyU4nbMwHuHP8njolJdSiUI6d6qVKq8cULQrBvXtKuW4+bMmA6SbG+TtMeyXzKXqpZsQ1UEsuyFHsfEyAIeLDERckvSC0Cymurf3BSF/5CUjK8V4Gh/okkUOk1ZPDKLlXJ8Nh8lUj2bsBphZX5169qSE5dsWIWhgGC3fhBv+6xHj+KNLZENZNIPqojDkJKTPxr7S2/NUKZDKHGEjNbbI0xfxJWpypT5H+xjh/BzkmAeOgO9HDnDp+Zbv+kBVDpZrKGZ0763cSbs/5tE3/tWy3TNJYzsoRPogx8/sZDuhIzX7J/NgZaKSJ2uzhXSoqCVCE7+AoaSjtEJQzdfJU6tH+8APkA827DUQrn66/9QnKlHB3Oc29PVFFBHsQ4E/zK5krhQcywjD3i5WGq97JAtqCliXOvOSaZDFr0JDzg4mRhkFkRwgkkdgMiKhVy+eNY8Zj1cz9KV4R8Irseeu5SKmH9+qVEMBdB+O2Mez1JqXX9KkGLzCgVv5cYvsgizel4d7Aar0EEK/fkr6Ms5U3sllzXo2L2NFxTETiVUI0BjwPiM01Q+QkRAGfCRQ1KPZrM58GoEE+Xqt9gnSL0y5eUQ9E+H07M3Mv9tlR7XUEZWDSHjuIedhjU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
