travis:
  secure:
    BINSTAR_TOKEN: T35CtizxxQCC1hAou6oN30d3tvUYLWMkYjBfHyycT3MlU4EPTShJVYXiueKKpA+HRAxP0zdN8ftikucNj9c83lGHvw9ArTvRAA+AmYgOxeSrnB1B26n6eOqaWgT0GwX8pwlPN1hpA5KH+WX/w6V4mz7oEbLQ8g/T2Higy9jcNkPz99M6BNGafYtgnqO/7o9lTjk9uELUIwZNSfjZecSuZhV/uWzNvf5T/EQ56Mqy0/1gE1roLUWFaP2SnYWf7LrUIemQr/Uo6IwMYEf2NgV4j9ChzEZCsu71FdS/Le3jHP1rZCiyqv1icAlEVaQ4XkRNWT8PtifSE+FWF3b+7FMRp8Eq+oUnyZErELqVMLkFX1sgptQDd5j4enPNUunPuCzR6n9pOHQQFlp0hLK9Wro34ZT5Ulkrt55yeI/r4FKjnRkCDlGog4T2C95DS2TQZ4/sANUlRDLvJy8hJomg4ab8dlJuJdq7Oq+OQGlvvsG92bdjOhdA7arVM71whGfMURcWO2oz0i11qATM7zBPLFczIb/9qgvOGtJvb2yWnJOBEPPvNaxv0LRURy5tXBmfj9Vjt18ravFwSvb/gQalXE++lP+Ztt+K6xUvv1kdeLWechVnn4pEF3n33WDKZa0v+CYUs5To9AT3CzVVQuYHwBl4Xj4/hw+GKS6zZPuVgPQRnzQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
