travis:
  secure:
    BINSTAR_TOKEN: JCGHsaTMGobcvZXSxuR1zk2b1xVF8E5p16cO0RofQCik4AJuyVUbmiGStFrFCl0067UAi+GqNZvKd367kbtkAepE5BKbMwOhEYgec5K4iYV4iuT5tU3B8dJ+el46J+dji/Un9isOadjdAU4nLEfcJ5z210bZYzPQqNBFq2YYXoSnqn2Wj9jpBxPiUtPlxvSdZaw+ZGPcCy1P7J7KHuhhFaHvAIa7S8w1SJmpxdi0jDaS16Dnjv6GSdv+J4pnJmlIsx2A5XslM+wKOVUTT9CJjawoq3Vfj5b3UFtt8kxls2piGjcYeUlN8FzobiFVbaSkZOCXKpaDgvivlN1VcdDql1oJzg67urNUeW+Ox3nQCP4v2SQ5yDdzHV0JZ5UyzRuNdFrVe8KYtTcbkclMgAUYLDXjrQjrOeqrcPkCVrdmAb1Kn694mK/bZTTvVFIKvM3yx7ci1JCqy0ph60BuZuaZkb2qozUupIwMk1N4iKMoaY8OVW2KXVco+JML9vnBPE64HZxXjHk+C7GbRTz+8H2T12D7VOOSBbPMg3E7hBmaLZvD94LFsvN8U5bSPzypbwA8sVdHpJLhn0jfXu0PeV7MfTEK0THTO51eMqvsfeLH/vMwlXlU8/m9sOIqGazfLTPPsYNomOMU11CB+ANJTYZ4VM5FRmryxhFLRrDaMvUS+aM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
